<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Note;
use App\Models\Answer;
use App\Models\Scheme;
use App\Models\Question;
use App\Models\Questionnaire;
use App\Models\QuestionScheme;
use App\Models\QuestionnaireAnswer;
use App\Models\QuestionnaireScheme;
use App\Models\QuestionnaireQuestion;

class QuestionnaireData extends Seeder{
    public function run(): void{
        Scheme::firstOrCreate(['title' => '']); // special scheme, referred to in analyses_answers, instead of setting NULL (important for compound unique index constraint)
        $schemes = array_map(fn($t) => Scheme::create(['title' => $t])->id, [
            'Own Funds',
            'Interacting/Internal Contracting',
            'Revolving Funds',
            'Soft Loans',
            'Green Bonds',
            'EPC',
            '3rd Party Financing',
            'Guarantee Funds',
            'On-bill financing',
            'Citizens Financing - Cooperatives/Crowdfunding'
        ]);

        $frc = static::newQuestionnaire('Quick Finance Readiness Check', [], false);
        $rdm = array_map(fn($a) => static::newQuestionnaire($a[0], array_map(fn($i) => $schemes[$i], $a[1])), [ // Add RDM questionnaires ([title, schemes])
            ['Public Buildings',    [0, 1, 2, 3, 4, 5, 6, 7, 8]],
            ['Private Buildings',   [0, 2, 3, 4, 5, 6, 7, 8, 9]],
            ['Transport',           [0, 1, 3, 4, 5, 8, 9]],
            ['Public Lighting',     [0, 2, 5, 7, 8]],
            ['Cross Sectoral',      [0, 2, 3, 4, 5, 6, 9]]
        ]);
        $both = array_merge([$frc], $rdm);

        static::newA($both, 'No', 0);
        static::newA($rdm, 'Partially', 1);
        static::newA($both, 'Yes', 2);

        array_map(fn($a) => static::newQ([$frc], $a[0], [], count($a) > 1 ? $a[1] : null), [    // Add FRC questions ([question, note?])
            ['Have you defined the **measures** that you intend to implement in your project?', 'These include all measures that result in energy savings or the production of renewable energies. You need to have a clear understanding of which measures you plan to implement in your project in order to understand the project costs and revenues.'],
            ['Has a baseline **energy consumption** been determined?', 'In order to calculate the impacts of your project, you need to know your baseline energy consumption before the implementation of any measures.'],
            ['Have you determined the energy savings and/or renewable energy production resulting from your planned measures?', 'In order to calculate the revenues of your project you need to have a clear understanding of your impacts in terms of energy savings and/or renewable energy produced.'],
            ['Have you calculated the **expected revenues from energy savings** and/or **the expected revenues from the selling of renewable energy** generated by your project over its lifetime?'],
            ['Have you calculated your **total investment costs** for the project?'],
            ['Have you developed a **budget** with all the costs for your project including operating costs?'],
            ['Have you determined the **payback period** for your project?', 'For this please also see our template on calculating financial indicators that you can find on our website.'],
            ['Have you assessed the **market conditions** for your project including **incentives and potential barriers**?'],
            ['Have you developed a **risk analysis** of potential risks or negative impacts your project might have?'],
            ['Have you developed a **working plan or roadmap** for the implementation of the project outlining the different steps and responsibilities?'],
            ['Have you developed an overview of the **governance structure** of the project, including roles and responsibilities and decision-making processes?'],
            ['Have you assessed any existing **helpful regulations or policies** that can support the development of your project?', 'It is important to understand which political factors or regulations can positively influence your project, including e.g. financial and regulatory incentives for energy efficiency measures, one-stop-shops, equal opportunities for public procurement, facilitated licensing for renewable energy projects, etc.'],
            ['Have you assessed any **challenging regulations or policies** that could pose a risk or barrier for your project?', 'It is important to understand which political factors or regulations negatively influence your project, such as e.g. long and bureaucratic licensing processes, requirements for impact assessments, land-use and ownership barriers etc.']
        ]);

        array_map(fn($a) => static::newQ($rdm, $a[0], array_map(fn($i) => $schemes[$i], array_diff(array_keys($schemes), array_key_exists(1, $a) ? $a[1] : [])), array_key_exists('note', $a) && $a['note'], array_key_exists('invertAnsVal', $a) && $a['invertAnsVal'], array_key_exists('splitSchemeAnswers', $a) && $a['splitSchemeAnswers']), [    // Add RDM questions ([question, disabled schemes?, 'invertAnsVal' => bool?, 'splitSchemeAnswers' => bool?])
            ["Has your municipality’s project been formally approved by your municipal council at a high political level?"],
            ["Is your municipality’s project linked to a national investment prioritization process directly supported by existing municipal budgets and/or dedicated national or international funding sources?", [3, 4, 5, 6, 7, 8, 9], 'note' => 'The question refers to supporting central government projects and/or long term national strategies that can serve as framework condition for mobilizing intergovernmental transfers to address differences in expenditure needs and fiscal capacity across cities, thus ensure the successful implementation of the respective local action plan or project.'],
            ["Does your city's project demonstrate a clear municipal ownership and direction on its strategic priorities, with a long-term finance orientation, considering potential options for refinancing or repaying investment (e.g. through energy bills or taxation etc)?", [6, 7], 'note' => 'Ownership may refer to different levels of government, including subnational government (regions and municipalities) and may take different legal forms such as public-private partnerships with local authorities, co-operatives, community trusts and foundations, limited liability companies, non-profit customer-owned enterprises, housing associations and municipal ownership. Local projects that demonstrate a clear ownership direction indicate an increased operational role of local authorities and their economic decisions that may lead for example to an increase of municipal control over a project’s management (e.g. setting up new or taking back control over existing local energy companies and energy infrastructure), whilst also improving transparency and accountability in public service delivery.'],
            ["Does your municipality’s project financing strategy foresee a mix of financial instruments and/or business models to create public-private partnerships, multiple financiers and service providers (e.g. for coordinating and mobilizing resources, sharing associated investment risks etc)?", [0, 1, 7]],
            ["Do public procurement procedures facilitate sustainable energy investments?"],
            ["Are subsidies, tax benefits, or other incentives or obligations (e.g energy savings, EEOs, etc) available for private project investors and lenders?", [0, 1, 3, 4, 7]],
            ["Do ownership issues with regard to municipality’s assets (e.g. buildings) facilitate the implementation of your local project related investments in these assets?"],
            ["Is the process to gain a construction/renovation permit fast and efficient?"],
            ["Are Budgetary Rules for local and regional authorities revised to exclude financing schemes (e.g. EPC) from debt quota obligations?", [0, 1, 7]],
            ["Does your municipality have the necessary resources to support the project’s development and implementation within the planned timeframe?"],
            ["Is the municipality’s personnel for project underwriting & evaluation able to support the implementation of the respective financing scheme?", [5], 'splitSchemeAnswers' => true],
            ["Does your municipality have the appropriate (multi-departmental) structure responsible for the ultimate oversight, including co-ordination, monitoring, performance risks management etc, over your city's project efficient implementation?"],
            ["Does your municipality have the necessary capacity to conduct business development activities among which investigating alternative funding sources?"],
            ["Does your municipality have the technical expertise to support the implementation of the respective financing scheme?", 'splitSchemeAnswers' => true],
            ["Can your municipality’s own capital (e.g. available city budget) support the implementation of the respective financing scheme?", [5, 6, 7, 8, 9], 'splitSchemeAnswers' => true],
            ["Does your municipality’s financing strategy analyse both public and private, domestic and international, potential funding sources for supporting the priorities identified?", [0]],
            ["Can your municipality capitalize from lending institutions to support the project’s implementation?", [0, 1]],
            ["Does the municipality have a history on default on debt?", [0, 3, 5, 7], 'invertAnsVal' => true],
            ["Is the typical nominal bank lending rate relatively low and/or attractive to your organization?", [0, 3, 5, 7, 9]],
            ["Is co-financing foreseen and detailed in your municipality’s project proposal budget?", [0, 1]],
            ["Will your municipality’s project utilize other innovative sources, such as levies?", [0, 1]],
            ["Does your municipality’s project describe how priority objectives will be translated into specific actions, utilizing new financial instruments or mobilizing finance from third development partners?"],
            ["Does the public stance support your municipality's project related investments within the planned timeframe?", 'note' => 'Public stance refers to public acceptance, participation and support. Poor public stance may lead to insufficient or poor involvement of public actors and key target groups in the project’s implementation.'],
            ["Are your municipality’s energy and climate action plans, projects and initiatives adequately disseminated to prospect investors and actors?"],
            ["Is the municipality’s cooperation and communication with public actors for SECAP or other investment projects adequate so as to implement the financing scheme?", [5], 'splitSchemeAnswers' => true],
            ["Is the municipality’s cooperation and communication with traditional private actors for SECAP or other investment projects (e.g. banks, utilities, energy providers, etc) sufficient in order to implement the scheme?", 'splitSchemeAnswers' => true],
            ["Is the municipality’s cooperation and communication with non-traditional investment actors (e.g. ESCOs) sufficient to implement the respective scheme?", [0, 3, 9], 'splitSchemeAnswers' => true],
            ["Is a Steering Committee or similar internal mechanism in place or planned as a governing body to fully oversee your municipality’s project implementation?"],
            ["Does the municipality plan to sub-contract its roles and responsibilities with respect to project implementation, and/or transfer all or part of the necessary proceeds,  to a third implementing entity either internal or external?", [0, 3, 4, 7]],
            ["In case the municipality plans to sub-contract and/or transfer all or part of the necessary proceeds, to a private third implementing entity is a clear explanation of the contractual arrangements, including transactional flow and/or flow of information, in place?", [0, 1, 3, 4, 7]],
            ["Is your municipality’s project anticipated duration and implementation schedule reasonable and fully coordinated with all relevant investment actors and stakeholders involved?"]
        ]);
    }

    public static function newQuestionnaire(string $title, array $schemeIDs, bool $isRDM = true){
        $qID = Questionnaire::create(['title' => $title, 'isRDM' => $isRDM])->id;
        foreach ($schemeIDs as $schemeID)
            QuestionnaireScheme::create([
                'scheme_id' => $schemeID,
                'questionnaire_id' => $qID
            ]);
        return $qID;
    }

    public static function newA(array $questionnaireIDs, string $answer, int $value){
        $aID = Answer::create(['answer' => $answer, 'value' => $value])->id;
        foreach ($questionnaireIDs as $questionnaireID)
            QuestionnaireAnswer::create([
                'questionnaire_id' => $questionnaireID,
                'answer_id' => $aID
            ]);
        return $aID;
    }

    public static function newQ(array $questionnaireIDs, string $question, array $schemeIDs, string $note = null, bool $invertAnsVal = false, bool $splitSchemeAnswers = false){
        $qID = Question::create([
            'question' => $question,
            'note_id' => $note ? Note::create(['note' => $note])->id : null,
            'invert_ans_val' => $invertAnsVal,
            'split_scheme_answers' => $splitSchemeAnswers
        ])->id;
        foreach ($schemeIDs as $schemeID)
            QuestionScheme::create([
                'scheme_id' => $schemeID,
                'question_id' => $qID
            ]);
        foreach ($questionnaireIDs as $questionnaireID)
            QuestionnaireQuestion::create([
                'questionnaire_id' => $questionnaireID,
                'question_id' => $qID
            ])->id;
        return $qID;
    }
}
