<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Note;
use App\Models\Answer;
use App\Models\Scheme;
use App\Models\Question;
use App\Models\Questionnaire;
use App\Models\QuestionScheme;
use App\Models\QuestionnaireAnswer;
use App\Models\QuestionnaireScheme;
use App\Models\QuestionnaireQuestion;

class QuestionnaireData extends Seeder{
    public function run(): void{
        $schemes = array_map(fn($t) => Scheme::create(['title' => $t])->id, [
            'Own Funds',
            'Interacting/Internal Contracting',
            'Revolving Funds',
            'Soft Loans',
            'Green Bonds',
            'EPC',
            '3rd Party Financing',
            'Guarantee Funds',
            'On-bill financing',
            'Citizens Financing - Cooperatives/Crowdfunding'
        ]);

        $frc = static::newQuestionnaire('Quick Finance Readiness Check', [], false);
        $rdm = array_map(fn($a) => static::newQuestionnaire($a[0], array_map(fn($i) => $schemes[$i], $a[1])), [ // Add RDM questionnaires ([title, schemes])
            ['Public Buildings',    [0, 1, 2, 3, 4, 5, 6, 7, 8]],
            ['Private Buildings',   [0, 2, 3, 4, 5, 6, 7, 8, 9]],
            ['Transport',           [0, 1, 3, 4, 5, 8, 9]],
            ['Public Lighting',     [0, 2, 5, 7, 8]],
            ['Cross Sectoral',      [0, 2, 3, 4, 5, 6, 9]]
        ]);
        $both = array_merge([$frc], $rdm);

        static::newA($both, 'No', 0);
        static::newA($rdm, 'Partially', 1);
        static::newA($both, 'Yes', 2);

        array_map(fn($a) => static::newQ([$frc], $a[0], [], count($a) > 1 ? $a[1] : null), [    // Add FRC questions ([question, note?])
            ['Have you defined the **measures** that you intend to implement in your project?', 'These include all measures that result in energy savings or the production of renewable energies. You need to have a clear understanding of which measures you plan to implement in your project in order to understand the project costs and revenues.'],
            ['Has a baseline **energy consumption** been determined?', 'In order to calculate the impacts of your project, you need to know your baseline energy consumption before the implementation of any measures.'],
            ['Have you determined the energy savings and/or renewable energy production resulting from your planned measures?', 'In order to calculate the revenues of your project you need to have a clear understanding of your impacts in terms of energy savings and/or renewable energy produced.'],
            ['Have you calculated the **expected revenues from energy savings** and/or **the expected revenues from the selling of renewable energy** generated by your project over its lifetime?'],
            ['Have you calculated your **total investment costs** for the project?'],
            ['Have you developed a **budget** with all the costs for your project including operating costs?'],
            ['Have you determined the **payback period** for your project?', 'For this please also see our template on calculating financial indicators that you can find on our website.'],
            ['Have you assessed the **market conditions** for your project including **incentives and potential barriers**?'],
            ['Have you developed a **risk analysis** of potential risks or negative impacts your project might have?'],
            ['Have you developed a **working plan or roadmap** for the implementation of the project outlining the different steps and responsibilities?'],
            ['Have you developed an overview of the **governance structure** of the project, including roles and responsibilities and decision-making processes?'],
            ['Have you assessed any existing **helpful regulations or policies** that can support the development of your project?', 'It is important to understand which political factors or regulations can positively influence your project, including e.g. financial and regulatory incentives for energy efficiency measures, one-stop-shops, equal opportunities for public procurement, facilitated licensing for renewable energy projects, etc.'],
            ['Have you assessed any **challenging regulations or policies** that could pose a risk or barrier for your project?', 'It is important to understand which political factors or regulations negatively influence your project, such as e.g. long and bureaucratic licensing processes, requirements for impact assessments, land-use and ownership barriers etc.']
        ]);

        array_map(fn($a) => static::newQ($rdm, $a[0], array_map(fn($i) => $schemes[$i], array_diff(array_keys($schemes), count($a) > 1 ? $a[1] : [])), null, array_key_exists('invertAnsVal', $a) && $a['invertAnsVal']), [    // Add RDM questions ([question, disabled schemes?, 'invertAnsVal' => bool?])
            ["Has your city's project been formally validated by your City's Council at a high political level?"],
            ["Does your city's project demonstrate a national investment prioritization process directly supported by existing municipal budgets and/or dedicated national or international funding sources?", [3, 4, 5, 6, 7, 8, 9]],
            ["Does your city's project demonstrate a clear national ownership and national direction on its strategic priorities, with a long-term finance orientation, considering potential options for refinancing or repaying investment (e.g. through energy bills or taxation etc)?", [6, 7]],
            ["Where feasible, does your city's project financing strategy provide for a mix of financial instruments and/or business models to create public-private partnerships, multiple financiers and service providers (e.g. for coordinating and mobilizing resources, sharing associated investment risks etc)?", [0, 1, 7]],
            ["Do public procurement procedures facilitate sustainable energy investments adequately?"],
            ["Are subsidies, tax benefits, or other incentives and obligations(e.g energy savings, EEOs, etc) available for private project investors and lenders?", [0, 1, 3, 4, 7]],
            ["Do ownership issues with regard to city's assets (e.g. buildings) facilitate the implementation of your city's project related investments in these assets?"],
            ["Is the process to gain a construction/renovation permit fast and efficient?"],
            ["Are Budgetary Rules for public and regional authorities revised to exclude financing schemes (e.g. EPC) from debt quota obligations?", [0, 1, 7]],
            ["Does your municipality have the necessary resources to support your city's project development and implementation within the planned timeframe?"],
            ["Is the city's personnel for project underwriting & evaluation sufficient to support the implementation of the respective financing scheme?", [5]],
            ["Does your municipality have the appropriate (multi-departmental) structure responsible for the ultimate oversight, including co-ordination, monitoring, performance risks management etc, over your city's project efficient implementation?"],
            ["Does your municipality have the necessary capacity to conduct business development activities among which investigating alternative funding sources?"],
            ["Does your municipality have the necessary know-how and/or technical expertise to support the implementation of the respective financing scheme?"],
            ["Are city's own capital requirements (e.g. available city budget) sufficient to implement the financing scheme?", [5, 6, 7, 8, 9]],
            ["Does your city's financing strategy analyze both public and private, domestic and international, potential funding sources for supporting the priorities identified?", [0]],
            ["Can your municipality capitalize from lending institutions to support your city's project implementation?", [0, 1]],
            ["Does the city have a history on default on debt?", [0, 3, 5, 7], 'invertAnsVal' => true],
            ["Is the typical nominal bank lending rate relatively low?", [0, 3, 5, 7, 9]],
            ["Is co-financing available and complete detail provided in your city's project proposal budget?", [0, 1]],
            ["Will your city's project utilize other innovative sources, such as levies?", [0, 1]],
            ["Does your city's project describe how priority objectives will be translated into specific concept notes, utilizing new financial instruments or mobilizing large scale finance from third development partners in the future?"],
            ["Does the public stance support your city's project related investments within the planned timeframe?"],
            ["Are your city's SECAP related projects and initiatives adequately disseminated to prospect investors and actors?"],
            ["Is the city's cooperation and communication with public actors for SECAP or other investment projects adequate so as to implement the financing scheme?", [5]],
            ["Is the city's cooperation and communication with traditional private actors for SECAP or other investment projects (e.g. banks, utilities, energy providers, etc) sufficient in order to implement the scheme?"],
            ["Is the city's cooperation and communication with non-traditional investment actors (e.g. ESCOs) sufficient to implement the respective scheme?", [0, 3, 9]],
            ["Is a Steering Committee or similar internal mechanism in place or planned as a governing body to fully oversee and guide your city's project implementation?"],
            ["Does the municipality plan to sub-contract its roles and responsibilities with respect to project implementation, and/or transfer all or part of the necessary proceeds,  to a third implementing entity either internal or external?", [0, 3, 4, 7]],
            ["In case the municipality plans to sub-contract and/or transfer all or part of the necessary proceeds, to a private third implementing entity is a clear explanation of the contractual arrangements, including transactional flow and/or flow of information, in place?", [0, 1, 3, 4, 7]],
            ["Is your city's project anticipated duration and implementation schedule reasonable and fully coordinated with all relevant investment actors and stakeholders involved?"]
        ]);
    }

    public static function newQuestionnaire(string $title, array $schemeIDs, bool $isRDM = true){
        $qID = Questionnaire::create(['title' => $title, 'isRDM' => $isRDM])->id;
        foreach ($schemeIDs as $schemeID)
            QuestionnaireScheme::create([
                'scheme_id' => $schemeID,
                'questionnaire_id' => $qID
            ]);
        return $qID;
    }

    public static function newA(array $questionnaireIDs, string $answer, int $value){
        $aID = Answer::create(['answer' => $answer, 'value' => $value])->id;
        foreach ($questionnaireIDs as $questionnaireID)
            QuestionnaireAnswer::create([
                'questionnaire_id' => $questionnaireID,
                'answer_id' => $aID
            ]);
        return $aID;
    }

    public static function newQ(array $questionnaireIDs, string $question, array $schemeIDs, string $note = null, bool $invertAnsVal = false){
        $qID = Question::create([
            'question' => $question,
            'note_id' => $note ? Note::create(['note' => $note])->id : null,
            'invert_ans_val' => $invertAnsVal
        ])->id;
        foreach ($schemeIDs as $schemeID)
            QuestionScheme::create([
                'scheme_id' => $schemeID,
                'question_id' => $qID
            ]);
        foreach ($questionnaireIDs as $questionnaireID)
            QuestionnaireQuestion::create([
                'questionnaire_id' => $questionnaireID,
                'question_id' => $qID
            ])->id;
        return $qID;
    }
}
